### PR TITLE
Use the suffix from the uri for the patch, if present.

### PR DESCRIPTION
**Pull request by AlexGhiondea**

### CODE REVIEW

**Comment by dwt12777** [comment]
@AlexGhiondea forgive my ignorance, but do I need to add your source locally to my solution to try this out?  Right now I just have SmugMug.Net.v2Api added as a nuget package, which I think means I can only run versions you've published (latest I'm seeing is -beta5).  I'm searching up how to do this, but wanted to ask here as well.

**Comment by AlexGhiondea** [comment]
@dwt12777 you can pull my fork and then add a project reference to my project, or I can share a package here if that is easier.

**Comment by dwt12777** [comment]
Let me try and do it the "right way" - standby...

**Comment by dwt12777** [comment]
Tested and it appears it's now handling all my image files, regardless of suffix.  I think we're in good shape!

**Comment by AlexGhiondea** [comment]
@dwt12777 I have published a beta6 of the package! I am going to try and spend some time this week and update the project (make is ns20, add build validation in CI, etc)!

**Pull request merged**
